name: Update Project Visualization URLs

on:
  push:
    paths:
      - '_visualizations/**'
      - 'python/data_entries.py'

jobs:
  update-visualizations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate project entries
        run: python python/data_entries.py

      - name: Commit updated projects.yml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/projects.yml
          git commit -m "Regenerate _data/projects.yml from _visualizations" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main